#------------------------------------------------------------------------------
# Developer---Cole Carter
# Course------CS3123-01
# Project-----Program #4
# Due---------April 18, 2025

# This makes the entire minesweeper program. 
#------------------------------------------------------------------------------

a.out: main.cpp minefield.cpp minefield.h cell.cpp cell.h
	g++ main.cpp minefield.cpp cell.cpp
clean:
	rm -f a.out *.o
